[sdl]
fullscreen=false
fulldouble=false
fullresolution=desktop
windowresolution=original
output=overlay

[dosbox]
memsize=16

[cpu]
core=auto
cycles=auto

[render]
aspect=true
scaler=normal2x

[midi]
mpu401=intelligent
mididevice=default
midiconfig=

[sblaster]
oplrate=44100

dsderive=true

[gus]
baserate=44100

[speaker]
rate=44100

[autoexec]
@echo off
mount c .
c:
path c:\watcom\binw;C:\
prompt [$p]$g
echo Building Brother prototype...
if exist brother.exe del brother.exe
wcl -fe=brother.exe src\main.c
brother.exe
